database_path: testfiles/test2db.db
repo: testfiles/test2.git
name: martin
email: m.e@acm.org
verbose: true
uniq_pfx: b
debug: false
item_dir: items
repo_branch: main
auto_link: true
url: git@work.jennyemily.hk:fanling/testrep2.git
no_write_to_server: false
ssh_path: /home/martin/.ssh/id_rsa
slurp_ssh: false
